### PR TITLE
feat(container-pull-script): store result from copy command

### PR DESCRIPTION
**Pull request by elruwen**
When integrating this script into an automated process, this output can be very useful, for example to feed the result into helm chart paramters automatically.

### CODE REVIEW

**Comment by carlosmmatos** [comment]
@elruwen thanks for opening up the PR. At this time, I don't think we want to add this specific functionality (although you are free to fork this project and make it work for you). 

With that being said, I think you are correct in that we should provide a proper stdout at the end of any copy operation to let users know the path the image was copied to... something like:

`image copied as: http://quay.io/test/falcon-sensor:7.19.0-5806.container.x86_64.Release.US-2`

**Comment by redhatrises** [comment]
Ideally, you would be using ArgoCD or FluxCD (better helm support) in conjunction with a GitOps process. If a GitOps tool can't be used for some reason, you should use a custom config.yaml file that is passed to helm that contains all of your desired configuration vs saying setting everything via command line flags. From there, you could use `--list-tags` to get the tags if so desired. Of course at that point, it would be better to use this script to just grab your pulltoken and use skopeo directly to copy everything over as well as using skopeo to get your tags.

**Comment by elruwen** [comment]
Even with gitops, I need the version number so I can write it to my argocd repo.

And then I need to parse the output of `--list-tags`. When I call the endpoint right now, the latest version is the last one in the list. But I don't see that behaviour somewhere documented. For a while this same endpoint was also listing sha256 sums at the end of this command, so if I would have blindly picked the last one I would have gotten something I don't want. That seems to be fixed now.

All doable, but imho unnecessarily complicated

**Comment by carlosmmatos** [comment]
> And then I need to parse the output of --list-tags. When I call the endpoint right now, the latest version is the last one in the list. But I don't see that behaviour somewhere documented.

Yes - the last one is the latest version. When you say it's not documented, are you saying that you want to see something that says: 

```shell
--list-tags                                    List all tags available for the selected sensor type and platform, sorted in ascending order
```

If so I think that is a valid ask. For context, we do the sorting here because the API's do not provide us with properly sorted output - and most tools like `jq` or even skopeo will not give you the correct sorted due to the fact that some of our containers are not in proper semver format. 

So just thinking here - currently we offer the `--get-image-path` which gives you:
- `registry/repository:latest-tag`

ex: `registry.crowdstrike.com/falcon-container/us-2/release/falcon-sensor:7.19.0-5806.container.x86_64.Release.US-2`

For me, this pretty much offers you all the information you would need to construct your copy-path in an automated fashion. I could see maybe just doing:
`--get-copy-path` to display the path where the image will get copied to, but at that point, my initial stdout of `Image copied as: ...` would be easy enough to get the same information.

**Comment by carlosmmatos** [comment]
We will not be merging this request. All the information is already there to build a copy-path if need be. As an example:
```bash
basename $(falcon-container-sensor-pull.sh -t falcon-container --get-image-path)
```
Will return your `repository:latest-tag`

And if you are already copying with the `-c, --copy` arg, then you already have your destination built-out.

**Pull request closed without merging**
