### PR TITLE
Update curl version logic

### LINKED ISSUE #174: Update curl version logic
The main issue with the existing logic is that we're comparing versions as integers, which isn't an accurate way to do version comparison. The reason is that version numbers are not integers; they're a series of integers. If version numbers were just integers, version 1.11 would be less than version 2.0 and also version 1.2. But it's not, because the 11 in 1.11 is not a single digit but two digits.

example:
```shell
curl 8.0.1 will be less than 7.55.0 because the comparison is:

if 801 < 7550
```

### PR DESCRIPTION
**Pull request by carlosmmatos**
Fixes #174

This PR enhances the logic used to test for curl version compatability.

### CODE REVIEW

**Comment by redhatrises** [comment]
I wonder if `sort -V` or something like https://apple.stackexchange.com/questions/83939/compare-multi-digit-version-numbers-in-bash/123408#123408 would be better.

**Review by ffalor — APPROVED** [review]

**Comment by ffalor** [comment]
Approved before I saw gabes comment. Changes LGTM, but I'll let you two decide what to do with that :)

**Comment by carlosmmatos** [comment]
> I wonder if `sort -V` or something like https://apple.stackexchange.com/questions/83939/compare-multi-digit-version-numbers-in-bash/123408#123408 would be better.

I went through a few different iterations.. each time stumbling upon the misery of supporting bash and dash lol... what I have here is easily readable and works for both.

The sort -V is an interesting approach - however I'm not sure how readable it is or if -V and -C options are supported on all versions lol..

**Comment by carlosmmatos** [comment]
@redhatrises This is what sort -V -C approach would look like:

```shell
old_curl=$(
    version=$(curl --version | head -n 1 | awk '{ print $2 }')
    minimum="7.55"

    # Check if the version is less than the minimum
    if echo -e "$version\n$minimum" | sort -V -C; then
        echo 0
    else
        echo 1
    fi
)
```

Other than the comment.. I wouldn't know wth is going on lol. What do you think?

**Comment by carlosmmatos** [comment]
@redhatrises code has been updated to work with `sort` as well as bash/dash

**Review by redhatrises — APPROVED** [review]

**Pull request merged**
