### PR TITLE
Initial commit for testing new curl syntx

### LINKED ISSUE #80: Issue with earlier version's of curl affecting api calls
May be a cause for issue #69 

## Symptom
The symptom here is that a successful access token is generated from the oauth2 api call. Then, any subsequent api calls via curl fail with: `"message": "access denied, invalid bearer token"`

## Affected Systems
Affected operating systems found thus far are RHEL 7 family. But after doing some research, I think the issue here has more to do with any system using Curl version < 7.55.0. 

This is because Curl has the following message for the `-H --header` option:
```
Starting in 7.55.0, this option can take an argument  in  @file-name  style, 
which then adds a header for each line in the input file. 
Using @- will make curl read the header file from stdin.
```

## Suggested Changes
Since most of our curl calls use the `-H @-` to read from stdin, for backwards compatibility, I propose the following changes as an example:
```diff
- cs_target_cid=$(echo "authorization: Bearer $cs_falcon_oauth_token" | curl -s -L "https://$(cs_cloud)/sensors/queries/installers/ccid/v1" -H @-)
+ cs_target_cid=$(curl -s -L "https://$(cs_cloud)/sensors/queries/installers/ccid/v1" -H "authorization: Bearer ${cs_falcon_oauth_token}")
```

Expect a PR soon

### PR DESCRIPTION
**Pull request by carlosmmatos**
Fixes #80

### CODE REVIEW

**Review by isimluk — COMMENTED** [review]
See 06c4a20495dae57beefa7efa9363186721a5d7ef

**Comment by carlosmmatos** [comment]
This is currently under review since there was an original PR that addressed the security concern of passing in sensitive credentials via stdout: https://github.com/CrowdStrike/falcon-scripts/commit/56ebbae03d342f98352f60ab1dde56d72c067840

**Comment by carlosmmatos** [comment]
@isimluk seriously!! dash doesn't support arrays!!!! 🤦🏼‍♂️

**Review by isimluk — APPROVED** [review]

**Comment by isimluk** [comment]
Looks good to me!

**Comment by isimluk** [comment]
thx

**Pull request merged**
