### PR TITLE
Get image repository and latest tag without downloading image

### PR DESCRIPTION
**Pull request by falcon-pioupiou**
Get image repository and latest tag without downloading image or listing all tags
Today it's not possible to get the image full path info without downloading the image.

really simple to use for end users to get the correct image path (which is useful also for automation).

### CODE REVIEW

**Comment by carlosmmatos** [comment]
@falcon-pioupiou this is great timing because @redhatrises and I had a conversation about this yesterday.

**Comment by carlosmmatos** [comment]
@redhatrises - thoughts on `--get-image-repo-tag` name?

**Comment by redhatrises** [comment]
I feel like `--get-latest-tag` would be more accurate. In general, listing tags should return the full path and not just the image name.

**Comment by falcon-pioupiou** [comment]
I'm afraid by the word `latest` as we don't have a `latest` tag, it could confuse people.

**Review by carlosmmatos — APPROVED** [review]
Approved

**Pull request merged**
