### PR TITLE
Add kpa

### PR DESCRIPTION
**Pull request by yannhowe**
Added KPA support
- added --k, --kubernetes-protection-agent flag
- Parameterized registry and image info, everything else mostly the same
- Updated readme
- Not tested on govcloud (unable to)
- Tested on mac, ubuntu, Amazon Linux 2 environments

### CODE REVIEW

**Comment by yannhowe** [comment]
Added KPA support
- added --k, --kubernetes-protection-agent flag
- Parameterized registry and image info, everything else mostly the same
- Updated readme
- Not tested on govcloud (unable to)
- Tested on mac, ubuntu, Amazon Linux 2 environments

**Review by carlosmmatos — APPROVED** [review]
LGTM

**Comment by falcon-pioupiou** [comment]
I will rework it to add the kac as well.

**Comment by carlosmmatos** [comment]
Closing as this was added in #186

**Pull request closed without merging**
